version: '3.5'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=dracco
    networks:
      - dracco

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./data/redis:/var/lib/redis
      - ./data/redis/conf:/usr/local/etc/redis/redis.conf
    networks:
      - dracco


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - dracco

networks:
  dracco:
    driver: bridge

